theme:
title: akmalrusli363
description: BINUSIAN 2022 Computer Scientist
image: /assets/opengraph.png

twitter:
  username: akmal_rusli
medium:
  username: akmalrusli363
linkedin:
  username: akmal-akmal-978189190

plugins:
  - jemoji
  - jekyll-gist
  - jekyll-linkpreview
  - jekyll-seo-tag
